### PR TITLE
fix crash on ios 11 when click save button

### PR DESCRIPTION
**Pull request by ITJesse**
https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html

### CODE REVIEW

**Comment by ITJesse** [comment]
2017-09-21 00:46:58.257821+0900 PxView[13654:2808397] [access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSPhotoLibraryAddUsageDescription key with a string value explaining to the user how the app uses this data.

**Comment by alphasp** [comment]
Thanks for your PR, can you update your PR by removing `NSPhotoLibraryAddUsageDescription` entry in `Info.plist`  and add `NSPhotoLibraryAddUsageDescription `in following `InfoPlist.strings` to support localization?
https://github.com/alphasp/pxview/blob/master/ios/Base.lproj/InfoPlist.strings
https://github.com/alphasp/pxview/blob/master/ios/en.lproj/InfoPlist.strings
https://github.com/alphasp/pxview/blob/master/ios/ja.lproj/InfoPlist.strings
https://github.com/alphasp/pxview/blob/master/ios/zh-Hans.lproj/InfoPlist.strings
https://github.com/alphasp/pxview/blob/master/ios/zh-Hant.lproj/InfoPlist.strings

**Comment by ITJesse** [comment]
Thanks for you reply, I will try it.

**Comment by ITJesse** [comment]
done!

**Pull request merged**
